common:
  # Dataset File Paths
  train_fn: "data/nikluge-sa-2022-train.jsonl"
  valid_fn: "data/nikluge-sa-2022-dev.jsonl"
  test_fn: "data/nikluge-sa-2022-test.jsonl"
# Model Configurations
models:
  roberta:
    model: 'xlm-roberta-base'
    max_length: 128
    batch_size: 8
    learning_rate: 3e-6
    eps: 1e-8
    num_epochs: 20
    hidden_size: 768
    dropout_p: 0.1
